name: animations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  get_it: ^7.7.0
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail:

flutter:
  uses-material-design: true
